repos:
  - repo: local
    hooks:
      - id: eslint
        name: eslint
        entry: npm run lint
        language: system
        pass_filenames: false
      - id: prettier
        name: prettier
        entry: npm run format
        language: system
        pass_filenames: false
